name: Metrics
on:
  # 毎日 00:00 UTC に更新
  schedule: [{cron: "0 0 * * *"}]
  # 手動更新も可能にする
  workflow_dispatch:
  # mainブランチへのプッシュ時に更新
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # --- 基本設定 ---
          token: ${{ secrets.METRICS_TOKEN }}
          user: botamochi-dev
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Tokyo
          repositories_affiliations: owner, collaborator
          
          # --- 言語統計 ---
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # --- コミットカレンダー  ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Recent Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_visibility: public

          # WakaTime
          plugin_wakatime: yes
          
