name: Metrics
on:
  # 毎日 00:00 UTC に更新
  schedule: [{cron: "0 0 * * *"}]
  # 手動更新も可能にする
  workflow_dispatch:
  # mainブランチへのプッシュ時に更新
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # --- 基本設定 ---
          token: ${{ secrets.METRICS_TOKEN }}
          user: botamochi-dev
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Tokyo

          # --- 言語統計 ---
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used

          # --- コミットカレンダー  ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # --- 開発実績  ---
          plugin_lines: yes
          
